spring:
  application:
    name: zuul-gateway
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

zuul:
  routes:
    aaa:
      path: /aaa/**
      serviceId: hello-service
    bbb:
      path: /bbb/**
      serviceId: feign-consumer