spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HelloWangmh/spring-cloud-learn
          search-paths: /config
          username: hellowangmh@163.com
          password:
server:
  port: 5555
